import Head from 'next/head';
import Hero from '../components/Hero';
import About from '../components/About';
import Scills from '../components/Scills';
import Projects from '../components/projects';
import Contacts from '../components/Contacts';

export default function Home() {
	return (
		<>
			<Head>
				<title>Fontend-End Developer</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Hero />
			<About />
			<Scills />
			<Projects />
			<Contacts />
		</>
	);
}

export const getStaticProps = async () => {
	return {
		props: {},
	};
};
